# Generated by Django 3.2 on 2022-04-21 15:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_auto_20220420_0745'),
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region', verbose_name='Departamento'), chained_model_field='region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city', verbose_name='Municipio'),
        ),
    ]
